import { Download, PackageSearch, Pencil, Plus, Search, Upload, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { NavLink, useLocation } from "react-router-dom";
import { api, downloadProtected } from "../api";
import { useAuth } from "../auth";
import { useTranslation } from "../i18n";
import { canAccess } from "../modules";

const inventoryStatuses=["In Stock","Allocated","Out of Inventory"];
const blank={status:"In Stock",country:"DEMO",project:"",category:"ITE",sub_category:"",number:"",donor:"",owner:"",designation:"",brand:"",model:"",serial_number:"",pr_reference:"",location:"Demo Field Office",assigned_user_id:"",user_name:"",date_last_inventory:"",purchasing_date:"",supplier:"",purchase_value:"",currency:"EUR",purchase_value_euros:"",depreciation_period:"",months_since_purchasing:"",current_value_euros:"",accessories:"",condition:"Good",remarks:"",outing_date:"",reason:"",additional_comments:""};
const groups=[
  ["1. Logistics Code",[["country","Country"],["project","Project"],["category","Category"],["sub_category","Sub-Category"],["number","Number"],["status","Status"]]],
  ["2. Ownership",[["donor","Donor"],["owner","Owner - Donor + Project Code"]]],
  ["3. Asset Designation",[["designation","Designation"],["brand","Brand"],["model","Model"],["serial_number","Serial Number"]]],
  ["4. Allocation",[["pr_reference","PR Reference"],["location","Location"],["assigned_user_id","Assigned User"],["date_last_inventory","Date of Last Inventory"]]],
  ["5. Invoice",[["purchasing_date","Purchase Date"],["supplier","Supplier"],["purchase_value","Purchase Value"],["currency","Currency"],["purchase_value_euros","Purchase Value Euros"],["depreciation_period","Depreciation Period (months)"],["months_since_purchasing","Months Since Purchase"],["current_value_euros","Current Value Euros"]]],
  ["6. Additional Information",[["accessories","Accessories"],["condition","Condition"],["remarks","Remarks"]]],
  ["7. Out of Inventory",[["outing_date","Date of Outing"],["reason","Reason"],["additional_comments","Additional Comments"]]],
];

export default function Inventory(){
  const {user}=useAuth();const {t}=useTranslation();const location=useLocation();
  const manage=canAccess(user,"can_manage_inventory");
  const requestedMode=location.pathname.includes("my-assets")?"my":"register";
  const mode=!manage?"my":requestedMode;
  const [data,setData]=useState({items:[],total:0,pages:0});const [page,setPage]=useState(1);const [q,setQ]=useState("");
  const [filters,setFilters]=useState({category:"",location:"",status:""});const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const [formOpen,setFormOpen]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState({...blank});
  const [assignees,setAssignees]=useState([]);
  const [importFile,setImportFile]=useState(null);const [importResult,setImportResult]=useState(null);const [importing,setImporting]=useState(false);
  useEffect(()=>{if(manage)api("/inventory/assignees?limit=100").then(setAssignees).catch(()=>{});},[manage]);
  async function load(){setLoading(true);setError("");try{if(mode==="my")setData(await api(`/inventory/my-assets?page=${page}&page_size=25`));else{const p=new URLSearchParams({page,page_size:25,...filters});if(q)p.set("q",q);setData(await api(`/inventory/items?${p}`));}}catch(err){setError(err.message);}finally{setLoading(false);}}
  useEffect(()=>{const timer=setTimeout(load,220);return()=>clearTimeout(timer);},[mode,page,q,filters.category,filters.location,filters.status]);
  function openForm(item=null){setEditing(item);setForm(item?{...blank,...item,assigned_user_id:item.assigned_user_id||""}:{...blank});setFormOpen(true);}
  async function save(e){e.preventDefault();setError("");try{const payload={...form,assigned_user_id:form.assigned_user_id?Number(form.assigned_user_id):null};await api(editing?`/inventory/items/${editing.id}`:"/inventory/items",{method:editing?"PUT":"POST",body:JSON.stringify(payload)});setFormOpen(false);setEditing(null);await load();}catch(err){setError(err.message);}}
  async function deactivate(item){if(!confirm(`Deactivate ${item.designation}?`))return;await api(`/inventory/items/${item.id}/deactivate`,{method:"PATCH"});load();}
  async function runImport(confirm=false){if(!importFile)return;setImporting(true);setError("");const body=new FormData();body.append("file",importFile);try{const result=await api(`/inventory/items/import?confirm=${confirm}`,{method:"POST",body});setImportResult(result);if(confirm)await load();}catch(err){setError(err.message);}finally{setImporting(false);}}
  const logisticsPreview=useMemo(()=>[form.country,form.project,form.category,form.sub_category,form.number].filter(Boolean).join("/"),[form.country,form.project,form.category,form.sub_category,form.number]);
  return <div>
    <div className="pagehead"><div><span className="eyebrow">Asset management</span><h1>IMS</h1><p>Asset register, staff assignments, valuation, and inventory tracking.</p></div>{mode==="register"&&manage&&<div className="actions">{canAccess(user,"can_import_inventory")&&<label className="secondary file-button"><Upload size={16}/>Import<input type="file" accept=".csv,.xlsx" onChange={e=>{setImportFile(e.target.files[0]||null);setImportResult(null);}}/></label>}{importFile&&canAccess(user,"can_import_inventory")&&<button className="secondary" disabled={importing} onClick={()=>runImport(false)}>{importing?"Checking…":"Preview Import"}</button>}{canAccess(user,"can_export_inventory")&&<button className="secondary" onClick={()=>downloadProtected("/inventory/items/export/csv","inventory-register.csv")}><Download size={16}/>{t("exportCsv")}</button>}<button className="primary" onClick={()=>openForm()}><Plus size={16}/>{t("addItem")}</button></div>}</div>
    <nav className="page-tabs">{manage&&<NavLink to="/inventory" end>Asset Register</NavLink>}<NavLink to="/inventory/my-assets">{t("myAssets")}</NavLink></nav>
    {error&&<div className="alert error">{error}</div>}
    {mode==="register"&&importResult&&<section className="panel import-summary"><div><strong>{importResult.total} rows checked</strong><span>{importResult.valid} valid · {importResult.imported} imported · {importResult.skipped} skipped · {importResult.invalid} errors</span></div>{importResult.imported===0&&importResult.valid>0&&<button className="primary" disabled={importing} onClick={()=>runImport(true)}>{importing?"Importing…":"Confirm Import"}</button>}<div className="import-errors">{importResult.rows.filter(row=>row.status==="invalid"||row.status==="skipped"||row.warnings?.length).slice(0,12).map(row=><p key={row.row}>Row {row.row}: {row.detail||row.warnings.join("; ")}</p>)}</div></section>}
    {mode==="register"&&<><section className="panel inventory-toolbar"><div className="queue-search"><Search/><input placeholder="Search designation, serial, brand, model or user…" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></div><input placeholder="Filter category" value={filters.category} onChange={e=>{setFilters({...filters,category:e.target.value});setPage(1);}}/><input placeholder="Filter location" value={filters.location} onChange={e=>{setFilters({...filters,location:e.target.value});setPage(1);}}/><select value={filters.status} onChange={e=>{setFilters({...filters,status:e.target.value});setPage(1);}}><option value="">All statuses</option>{inventoryStatuses.map(status=><option key={status}>{status}</option>)}</select></section>
      {formOpen&&<form className="panel inventory-form grouped-form" onSubmit={save}><div className="panel-title"><div><span className="eyebrow">{editing?"Edit asset":"New asset"}</span><h2>{form.designation||"Inventory asset"}</h2><p className="code-preview">Logistics code preview: <strong>{logisticsPreview||"Complete Section 1"}</strong></p></div><button type="button" className="icon" onClick={()=>setFormOpen(false)}><X/></button></div>
        {groups.map(([title,fields])=><fieldset key={title}><legend>{title}</legend><div className="grid three">{fields.map(([key,label])=><label key={key}>{label}{key==="assigned_user_id"?<select value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="">Unassigned</option>{assignees.map(person=><option key={person.id} value={person.id}>{person.full_name} · {person.department||"No department"}</option>)}</select>:key==="status"?<select required value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{inventoryStatuses.map(status=><option key={status}>{status}</option>)}</select>:["remarks","accessories","reason","additional_comments"].includes(key)?<textarea rows="2" value={form[key]||""} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input type={["purchasing_date","date_last_inventory","outing_date"].includes(key)?"date":"text"} required={["designation","category","location"].includes(key)} value={form[key]||""} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}</div></fieldset>)}
        <div className="form-actions"><button className="primary">{t("save")}</button><button type="button" className="ghost" onClick={()=>setFormOpen(false)}>{t("cancel")}</button></div>
      </form>}
    </>}
    <section className="panel tablewrap inventory-table">{loading?<div className="loading"><i/>{t("loading")}</div>:data.items?.length===0?<div className="empty"><PackageSearch/><h3>{mode==="my"?"No assets are assigned to you":"No inventory records"}</h3><p>{mode==="my"?"Assigned assets will appear here automatically.":"Add a record or adjust the filters."}</p></div>:<table><thead><tr><th>Logistics Code</th><th>Designation</th><th>Brand / Model</th><th>Serial</th><th>Location</th><th>Assigned User</th><th>Donor / Project</th><th>Condition</th><th>Current EUR</th><th>Status</th>{mode==="register"&&manage&&<th/>}</tr></thead><tbody>{(data.items||[]).map(item=><tr key={item.id}><td><strong>{item.logistics_code}</strong></td><td>{item.designation}<span>{item.sub_category}</span></td><td>{item.brand||"—"}<span>{item.model}</span></td><td>{item.serial_number||"—"}</td><td>{item.location}</td><td>{item.assigned_user_name||"Unassigned"}</td><td>{item.donor||"—"}<span>{item.project}</span></td><td>{item.condition||"—"}</td><td>{item.current_value_euros||"—"}</td><td><span className={`badge ${item.is_active?"active":"disabled"}`}>{item.status}</span></td>{mode==="register"&&manage&&<td><div className="row-actions"><button className="icon" onClick={()=>openForm(item)}><Pencil size={15}/></button><button className="icon danger" onClick={()=>deactivate(item)}><X size={15}/></button></div></td>}</tr>)}</tbody></table>}</section>
    <div className="pagination"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>{page} / {Math.max(data.pages,1)} · {data.total} records</span><button disabled={page>=data.pages} onClick={()=>setPage(page+1)}>Next</button></div>
  </div>;
}

