import { Save, Server, Wifi } from "lucide-react";
import { useEffect, useState } from "react";
import { api } from "../api";

export default function LanMessengerSettings(){
  const [form,setForm]=useState(null);const [error,setError]=useState("");const [saved,setSaved]=useState(false);
  useEffect(()=>{api("/lan-messenger/settings").then(data=>setForm({...data,lan_cidrs:(data.lan_cidrs||[]).join(", ")})).catch(err=>setError(err.message));},[]);
  async function submit(e){e.preventDefault();setError("");setSaved(false);try{const data=await api("/lan-messenger/settings",{method:"PUT",body:JSON.stringify({...form,lan_cidrs:form.lan_cidrs.split(",").map(x=>x.trim()).filter(Boolean)})});setForm({...data,lan_cidrs:data.lan_cidrs.join(", ")});setSaved(true);}catch(err){setError(err.message);}}
  if(!form)return <div className="loading"><i/>Loading LAN settings…</div>;
  const toggles=[["enabled","Enable LAN Messenger"],["allow_direct_messages","Direct messages"],["allow_groups","Groups"],["allow_channels","Channels"],["allow_meetings","Meetings"],["allow_file_uploads","File uploads"],["allow_voice_calls","Voice calls"],["allow_video_calls","Video calls"],["allow_group_voice_calls","Group voice calls"],["allow_group_video_calls","Group video calls"],["allow_meeting_calls","Meeting calls"],["prefer_lan_for_private_ips","Prefer LAN for private IPs"],["allow_external_access","Allow external access"]];
  return <div className="narrow-page"><div className="pagehead"><div><span className="eyebrow">Admin Center</span><h1>LAN Messenger Settings</h1><p>Control LAN/public routing and communication features.</p></div></div>{error&&<div className="alert error">{error}</div>}{saved&&<div className="alert success">LAN Messenger settings saved.</div>}<form className="panel sign-settings-form" onSubmit={submit}><div className="network-summary"><Wifi/><span><strong>Detected network: {form.detected_network}</strong><small>Preferred base URL: {form.preferred_base_url||"Current browser origin"}</small></span></div><div className="grid two"><label><Server/> Internal LAN base URL<input placeholder="http://192.168.1.22:8000" value={form.internal_lan_base_url||""} onChange={e=>setForm({...form,internal_lan_base_url:e.target.value||null})}/></label><label>Public base URL<input placeholder="https://demo.example.org" value={form.public_base_url||""} onChange={e=>setForm({...form,public_base_url:e.target.value||null})}/></label></div><label>LAN CIDR ranges<input value={form.lan_cidrs} onChange={e=>setForm({...form,lan_cidrs:e.target.value})}/><small>Comma-separated ranges.</small></label><label>Maximum attachment size (MB)<input type="number" min="1" max="100" value={form.max_file_size_mb} onChange={e=>setForm({...form,max_file_size_mb:Number(e.target.value)})}/></label><div className="lan-setting-grid">{toggles.map(([key,label])=><label className="switch-row" key={key}><span><strong>{label}</strong></span><input type="checkbox" checked={form[key]} onChange={e=>setForm({...form,[key]:e.target.checked})}/></label>)}</div><button className="primary"><Save/>Save settings</button></form></div>
}

