import { useEffect, useState } from "react";
import { api } from "../api";

export default function SignSettings(){
  const [form,setForm]=useState(null);const [error,setError]=useState("");const [message,setMessage]=useState("");
  useEffect(()=>{api("/admin/sign/settings").then(setForm).catch(err=>setError(err.message));},[]);
  async function save(event){event.preventDefault();setError("");try{setForm(await api("/admin/sign/settings",{method:"PUT",body:JSON.stringify(form)}));setMessage("Sign settings saved.");}catch(err){setError(err.message);}}
  if(!form)return <div className="loading"><i/>Loading settings...</div>;
  return <div className="narrow-page"><div className="pagehead"><div><span className="eyebrow">Admin Center</span><h1>Sign settings</h1><p>Control internal signing policy, token lifetime, email, and signature requirements.</p></div></div><form className="panel sign-settings-form" onSubmit={save}>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<label className="switch-row"><span>Enable digital signing<small>Allow users to create and process signing envelopes.</small></span><input type="checkbox" checked={form.is_enabled} onChange={e=>setForm({...form,is_enabled:e.target.checked})}/></label><label className="switch-row"><span>Require signature image<small>When disabled, a typed signature stamp is allowed.</small></span><input type="checkbox" checked={form.require_signature_image} onChange={e=>setForm({...form,require_signature_image:e.target.checked})}/></label><label className="switch-row"><span>Email notifications<small>Use SMTP when configured; otherwise log the link in development.</small></span><input type="checkbox" checked={form.email_notification_enabled} onChange={e=>setForm({...form,email_notification_enabled:e.target.checked})}/></label><div className="grid two"><label>Token expiry hours<input type="number" min="1" max="720" value={form.default_token_expiry_hours} onChange={e=>setForm({...form,default_token_expiry_hours:Number(e.target.value)})}/></label><label>Signature stamp position<select value={form.signature_stamp_position} onChange={e=>setForm({...form,signature_stamp_position:e.target.value})}><option value="signature_page">Signature page</option><option value="bottom_page">Bottom page (future)</option></select></label></div><button className="primary">Save settings</button></form></div>;
}
