INVENTORY_STATUSES = ("In Stock", "Allocated", "Out of Inventory")

INVENTORY_EXPORT_COLUMNS = [
    ("Status", "status"),
    ("Country", "country"),
    ("Project", "project"),
    ("Category", "category"),
    ("Sub-Category", "sub_category"),
    ("Number", "number"),
    ("Donor", "donor"),
    ("Owner\nDonor + Project Code", "owner"),
    ("Designation", "designation"),
    ("Brand", "brand"),
    ("Model", "model"),
    ("Serial number", "serial_number"),
    ("PR Reference", "pr_reference"),
    ("Location (Coo, Base 1 etc…)", "location"),
    ("User", "user_name"),
    ("Date of last Inventory", "date_last_inventory"),
    ("Purchasing date\nDD/MM/YYYY", "purchasing_date"),
    ("Supplier", "supplier"),
    ("Purchase Value\n(Currency of Purchase)", "purchase_value"),
    ("Currency", "currency"),
    ("Purchase Value\n(Euros)", "purchase_value_euros"),
    ('Depreciation period (Number of Month)\n(See Tab "Category")', "depreciation_period"),
    ("Number of Month since purchasing", "months_since_purchasing"),
    ("Current Value Euros", "current_value_euros"),
    ("Accessories", "accessories"),
    ("Condition", "condition"),
    ("Remarks", "remarks"),
    ("Date of outing\nDD/MM/YYYY", "outing_date"),
    ("Reason", "reason"),
    ("Additional comments if needed", "additional_comments"),
]
